#!/bin/bash


echo -n "Sisestage oma vanus: " #print
read vanus
if test $vanus -gt 0 -a $vanus -lt 11 #Laps kuni 11 eluaastane
then
	echo "Oled laps"

elif test $vanus -ge 11 -a $vanus -lt 18

then
	echo "Oled nooruk"

elif test  $vanus -ge 18 -a $vanus -lt 63

then
	echo "Oled täiskasvanu"

elif test $vanus -ge 63 # Oled eakas
then
	echo "Oled eakas"

else	
 	echo "sisendi viga"

fi
