#!/bin/bash
#
#!/bin/bash
#
#Kasutaja tervitus
#
#Skripti algus
#
#echo  "Tere User!"
echo -n "Tere " 
echo -n `who  am i | cut -c1 | tr [:lower:] [:upper:]` #Lõikab esimese tähe ja muudab suureks
echo -n `who am i | cut -c2-` #Lõikab tähed alates 2-st
echo "!"
#
#skripti lõpp
