#!/bin/bash
# kasutajate nimekiri kujul perenimi, eesnimi
# 
# skripti algus
# 
who | cut -f1 -d" " | cut -f2 -d"." > perenimi # lõikame perenime - see on 2. element peale punkti ja salvestame faili
who | cut -f1 -d" " | cut -f1 -d"." > eesnimi # lõikame eesnime - see on 1.element enne punkti ja salvestame fiali
paste -d "." perenimi eesnimi > nimed # kleebime elemendid kokku
 cat nimed | sort | uniq # sorteerime väljundi ja võtame korduvad välja  
